theme: jekyll-theme-hacker

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "^_^"
sidebar-avatar:1218824210.jpg      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
